apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: linkwarden
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - secretRef:
                name: linkwarden-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-linkwarden-postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: pvc-linkwarden-postgres
          persistentVolumeClaim:
            claimName: pvc-linkwarden-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkwarden
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres