apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grist
  namespace: grist
spec:
  volumeName: pv-grist
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grist
  namespace: grist
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/grist

    