apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grist-postgres
  namespace: grist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
