apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich-library
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Gi
