apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-leantime-private
  namespace: leantime
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi