apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-postgres
  namespace: immich
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: immich-secret
                key: DB_DATABASE_NAME
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-immich-postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: pvc-immich-postgres
          persistentVolumeClaim:
            claimName: pvc-immich-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
