apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1
  imageName: docker.io/tensorchord/cloudnative-vectorchord:16-0.4.3
  storage:
    size: 10Gi
    storageClass: longhorn
  postgresql:
    shared_preload_libraries:
      - vchord
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db
      postInitSQL:
        - "CREATE EXTENSION IF NOT EXISTS vector;"
        - "CREATE EXTENSION IF NOT EXISTS vchord CASCADE;"
        - "CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;"
