apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: immich
spec:
  selector:
    matchLabels:
      app: immich-redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
        - name: immich-redis
          image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
---

apiVersion: v1
kind: Service
metadata:
  name: immich-redis
  namespace: immich
  labels:
    app: immich-redis
spec:
  ports:
    - port: 6379
  selector:
    app: immich-redis
