apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-app
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak-app
          image: quay.io/keycloak/keycloak:latest
          args: ["start"]
          envFrom:
            - secretRef:
                name: keycloak-secret
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-app
  namespace: keycloak
  labels:
    app: keycloak-app
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: keycloak-app

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-app
  namespace: keycloak
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - "keycloak"
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-app
            port:
              number: 80