apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: keycloak
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KC_DB_URL_DATABASE
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pvc-keycloak-postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
      volumes:
        - name: pvc-keycloak-postgres
          persistentVolumeClaim:
            claimName: pvc-keycloak-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: keycloak
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: postgres