apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-langflow-postgres
  namespace: langflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
