apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-linkwarden-postgres
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi