apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak-postgres
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi