apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-outline
  namespace: outline
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi

    