apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: outline
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          volumeMounts:
            - mountPath: /redis.conf
              name: pvc-redis
          imagePullPolicy: Always 
          ports:
            - containerPort: 6379
          resources: {}
      volumes:
        - name: pvc-redis
          persistentVolumeClaim:
            claimName: pvc-redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: outline
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
